config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tasks

  root to: "tasks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!

  def index
    @tasks = current_user.tasks
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.users = @task.users.presence || [current_user]
    @task.save

    redirect_to action: "index"
  end

  private

  def task_params
    params.require(:task).permit(:title, :completed, :users)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hypertasking</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <div class="container">
        <h1>
          <%= link_to "Hypertasking", root_path %>
        </h1>

        <nav>
          <% if user_signed_in? %>
            <%= current_user.email %>
            <%=
              link_to(
                "Log Out",
                destroy_user_session_path,
                method: :delete
              )
            %>
          <% else %>
            <%= link_to "Sign Up", new_user_registration_path %>
            <%= link_to "Log In", new_user_session_path %>
          <% end %>
        </nav>
      </div>
    </header>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_task.html.erb
<li><%= task.title %></li>

app/views/tasks/index.html.erb
<h2>Tasks</h2>

<%= link_to "Add a task", new_task_path %>

<ul>
  <%= render @tasks %>
</ul>

app/views/tasks/new.html.erb
<h2>What do you need to do?</h2>

<%= form_for @task do |form| %>
  <%= form.text_field :title %>
  <%= form.submit "Remember" %>
<% end %>